/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.powerfitcontrol
import androidx.compose.runtime.Composable
import androidx.compose.ui.window.application
import androidx.compose.ui.window.Window
import androidx.compose.material.Text
import androidx.compose.runtime.LaunchedEffect
import br.com.powerfitcontrol.utils.getDatabasePath
import br.com.powerfitcontrol.utils.StringResources
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.dao.id.IntIdTable
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.SchemaUtils.create

object User: IntIdTable() {
    val name = varchar(name="name", length=255)
}

@Composable
fun App() {
    LaunchedEffect(Unit) {
        val databaseUrl = getDatabasePath()
        Database.connect("jdbc:sqlite:$databaseUrl", "org.sqlite.JDBC")
        transaction {
            create(User)
        }
    }
    Text("FRAN")
}

fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = StringResources.getString("app_name")
    ) {
        App()
    }
}
