/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.academytool
import androidx.compose.runtime.Composable
import androidx.compose.ui.window.application
import androidx.compose.ui.window.Window
import androidx.compose.material.Text

@Composable
fun App() {
    Text("FRAN")
}

fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "Academy Tool"
    ) {
        App()
    }
}
