/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.powerfitctrl.app

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
    }
}
