/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.powerfitcontrol

import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import br.com.powerfitcontrol.utils.StringResources
import br.com.powerfitcontrol.utils.getDatabasePath
import org.jetbrains.exposed.dao.id.IntIdTable
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils.create
import br.com.
import org.jetbrains.exposed.sql.transactions.transaction

object User : IntIdTable() {
    val name = varchar(name = "name", length = 255)
}

@Composable
fun App() {
    LaunchedEffect(Unit) {
        val databaseUrl = getDatabasePath()
        Database.connect("jdbc:sqlite:$databaseUrl", "org.sqlite.JDBC")
        transaction { create(User) }
    }
    Text("FRAN")
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication, title = StringResources.getString("app_name")) {
        App()
    }
}
